---
# This file (which would be located at roles/prometheus_install/handlers/main.yml)
# contains the handlers that are triggered by the tasks above.

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted